runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  MONGODB_URI: YOUR_MONGODB_URI
  ALLOWED_ORIGINS: https://www.pollnest.com/

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  target_throughput_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always

env: standard


